In [50]:
import torch
import time
torch.cuda.is_available()

True

In [51]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [54]:
A = torch.randint(0, 2, (2, 2), device=device)
B = torch.randint(2, 4, (2, 2), device=device)

prog = 2
row_sums = A.sum(dim=1)
mask = row_sums >= prog

result = torch.mm(A[mask].float(), B.float()).to(torch.long)

print(A)
print(B)
print(result)

tensor([[1, 1],
        [1, 0]], device='cuda:0')
tensor([[2, 3],
        [3, 2]], device='cuda:0')
tensor([[5, 5]], device='cuda:0')


In [55]:
size=10000
A_cpu = torch.randn(size, size)
start_cpu = time.time()
res_cpu = torch.mm(A_cpu.t(), A_cpu)
end_cpu = time.time()
print(f"CPU {end_cpu - start_cpu}")

A_gpu = torch.randn(size, size, device=device)

start_gpu = time.time()
res_gpu = torch.mm(A_gpu.t(), A_gpu)
torch.cuda.synchronize()
end_gpu = time.time()

print(f"GPU {end_gpu - start_gpu}")


CPU 3.7069599628448486
GPU 0.35691237449645996
